add : Upload NFF chap01 doc
gdsc-ssu/2023-FE-with-no-framework pull request #1
Opened 2023-01-04 15:01 UTC by yoo-jimin127

## Summary ✏️
NFF 1장 요약 문서 PR 날립니다!!
오타나 추가 or 수정할 내용들 자유롭게 피드백 부탁드려요!
확인 완료 되시면 merge 이후 gitbook에 올려두겠습니다 ☺️

reviewer auto assign이랑 PR 템플릿 추가해뒀는데,
제가 조금 늦은 시간에 재찬님이랑 서현님께 레포 초대 요청을 보내서 아직 리뷰어에 추가는 안되었어요 🥲
승인해주시는대로 다시 확인해보겠습니다!

## PR Check List ✔️
- [x] commit convention에 맞게 PR title 작성
- [x] assignees 추가
- [x] label & reviewers 확인
- [ ] 도서 정리 & 요약 내용 [gitbook](https://app.gitbook.com/o/yHUlx6TNN2gfJHHHSoU2/home) 추가

2023-01-04 16:28 UTC, aube-dev requested changes
정리 너무 수고하셨습니다! 👍 내용 작성 너무 잘해주셨지만 수정 제안할 내용이 조금 있어요!

2023-01-04 16:28 UTC, aube-dev commented on 01. 프레임워크에 대한 이야기/README.md
> +    → `loadash`를 사용해 배열 or 객체를 조작하거나 `Moment.js`를 사용해 날짜를 파싱하기도 함
사소한 오타가 있습니다!
```suggestion
    → `lodash`를 사용해 배열 or 객체를 조작하거나 `Moment.js`를 사용해 날짜를 파싱하기도 함     
```

2023-01-04 16:28 UTC, aube-dev commented on 01. 프레임워크에 대한 이야기/README.md
> +→ 저자가 리액트가 라이브러리가 아닌 프레임워크라고 믿는 이유
왜 명령형 패턴 코드가 리액트를 프레임워크라고 생각하게 하는지 부연 설명이 있으면 어떨까요? 책을 보고 나면 이  코드가 리액트답지 않아 어색하다고 느끼는 시점에서 그렇다는 것을 알게 되는데, 책을 옆에 두고 보지 않으면 헷갈리지 않을까 싶어요!

2023-01-04 16:28 UTC, aube-dev commented on 01. 프레임워크에 대한 이야기/README.md
> +        </div>
사소하긴 하지만...ㅎㅎ 이 부분을 들여쓰기하면 어떨까요?

2023-01-04 16:28 UTC, aube-dev commented on 01. 프레임워크에 대한 이야기/README.md
> +import moment 'moment';
사소한 오타가 있습니다!
```suggestion
import moment from 'moment';
```

2023-01-04 16:47 UTC, itjustbong commented on 01. 프레임워크에 대한 이야기/README.md
> +- 이전 AngularJS : **서비스 로케이터 패턴**을 기반으로 하는 의존성 주입 메커니즘 존재
서비스 로케이터 패턴에 대한 설명이 포함되면 좋을 것 같아서, 마틴 아저씨의 블로그 글을 추가했습니다

```suggestion
- 이전 AngularJS : **[서비스 로케이터 패턴](https://martinfowler.com/articles/injection.html#UsingAServiceLocator)**을 기반으로 하는 의존성 주입 메커니즘 존재
```

2023-01-04 16:50 UTC, itjustbong commented on 01. 프레임워크에 대한 이야기/README.md
> +
위 내용에서 의존성 주입과 서비스 로케이터 패턴에 대한 설명이 있으면 좋을 것 같아서,
해당 내용을 잘 작성해주신 마틴 아저씨의 블로그 글을 첨부합니다!
```suggestion
[Inversion of Control Containers and the Dependency Injection pattern](https://martinfowler.com/articles/injection.html#UsingAServiceLocator)

[번역본](https://javacan.tistory.com/entry/120)
```

2023-01-04 16:52 UTC, itjustbong commented on 01. 프레임워크에 대한 이야기/README.md
> +- 앵귤러 : 옵저버블을 사용한 반응형 프로그래밍용 라이브러리 `RxJS`를 기반으로 설계됨
RxJS에 대해서 이해하는데 큰 도움을 받았던,,, 테오님의 글을 첨부합니다

```suggestion
- 앵귤러 : 옵저버블을 사용한 반응형 프로그래밍용 라이브러리 `[RxJS](https://velog.io/@teo/rxjs)`를 기반으로 설계됨
```

2023-01-04 17:09 UTC, itjustbong commented on 01. 프레임워크에 대한 이야기/README.md
> +
선언적 방식과 명령형 방식에 대한 설명이 포함되면 좋을 것 같아 추가합니다!

```suggestion
[명령형 VS 선언형 프로그래밍](https://iborymagic.tistory.com/73)
```

2023-01-04 17:13 UTC, itjustbong commented on 01. 프레임워크에 대한 이야기/README.md
> +    - 대규모 애플리케이션에 적합하지 않아 많은 개발자들이 AngularJS를 떠나게 됨
왜 떠났는지에 대한 설명이 추가되면 좋을 것 같습니다!만 뭔가 명확한 글이 안보여 그냥 데이터 바인딩 특징 정리한 글 첨부 합니다!

```suggestion
    - 대규모 애플리케이션에 적합하지 않아 많은 개발자들이 AngularJS를 떠나게 됨
    - [양방향 바인딩 VS 단방향 바인딩 - 장단점](https://velog.io/@sunaaank/data-binding)
```

2023-01-04 17:19 UTC, itjustbong requested changes
와우... 역시 갓리나입니다 🥳
정리 깔끔하면서 코드도 다 작성해주셨네요..!
수고하셨습니다 👏

저는 이 책을 읽으면서 키워드들을 이해하는데 도움을 받았던, 그리고 다른 분들에게도 도움이 될 수 있을 것 같은 블로그 링크들을 첨부했습니다.

와 근데... 저 뭐지... 리뷰 좀 이상하게 했는데, 이거 정상적으로 어케 돌리죠...ㅋㅋㅋㅋ 너무 생각없이 했네요ㅠㅠㅠ

2023-01-04 17:32 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +    → `loadash`를 사용해 배열 or 객체를 조작하거나 `Moment.js`를 사용해 날짜를 파싱하기도 함
우와 너무 꼼꼼하게 봐주셔서 정말 감사합니다 !! 🤩
책 22p **프레임워크란?** 세번째 문단에
로대쉬<sup>Loadash</sup> 라고 적혀있어 그대로 썼던 것 같은데, 본 라이브러리를 사용한 코드에서는 `lodash`로 표기하네요!!
수정하겠숩니다 !!

2023-01-04 17:45 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +→ 저자가 리액트가 라이브러리가 아닌 프레임워크라고 믿는 이유
@aube-dev 오옹 너무 좋은 지적인 것 같아요!! 
저도 책을 요약할 땐 당연하게 넘어갔는데, 이 문서만을 본다면 부연설명이 필요할 것 같네요!!
추가해두겠습니다!!

2023-01-04 17:48 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +
오와 ... 너무 감사합니다!! 😆

2023-01-04 17:50 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +- 앵귤러 : 옵저버블을 사용한 반응형 프로그래밍용 라이브러리 `RxJS`를 기반으로 설계됨
호우 ... 감사의 말씀과 함께 ... RxJS를 이해하지 않고 냅다 적어버린 제 자신에게 잠깐 뭐라고 하고 올게요
좋은 자료 공유 감사합니다!!!

2023-01-04 17:52 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +
리뷰의 순기능 ... 점점 질좋은 자료가 되어가는 것 같아서 넘 좋네요 ... 감삼다 !!!

2023-01-04 18:00 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +    - 대규모 애플리케이션에 적합하지 않아 많은 개발자들이 AngularJS를 떠나게 됨
저도 앵귤러JS 떠난 이유와 관련된 링크를 찾아보고 있었는데 .. 링크로 첨부하기에 조금 적합하지 않은 자료들만 발견해서 .. 🥲
승우님께서 첨부해주신 자료인 데이터 바인딩 측면에서 앵귤러JS의 망..조..(?)를 어느정도 뒷받침할 수 있을 것 같아요!!
좋은 자료 너무 감사드립니다~!

2023-01-04 18:26 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +        </div>
반영했습니당 감사해요!! ☺️ 
여담인데 ㅋㅋㅋㅋ 들여쓰기 지적해주셔서 고치다가 저기 Toggle 옆 닫는 button태그에 요상한 기호를 사용했단걸 알아챘어요 ...
이거 완전 개발자 울리기 딱 좋은 .... 당장 없애고 고쳤습니다 ㅋㅋㅋㅋㅋㅋ

2023-01-05 12:41 UTC, hjch0211 reviewed
수고 많으셨습니다! 👍👍

2023-01-05 12:41 UTC, hjch0211 commented on 01. 프레임워크에 대한 이야기/README.md
> +    - [양방향 바인딩 VS 단방향 바인딩 - 장단점](https://velog.io/@sunaaank/data-binding)
저는 양방향 데이터 바인딩을 하면, 코드가 복잡해진다고 생각했는데...
디자인 패턴과 달리 데이터 바인딩에서는 양방향 데이터 바인딩이 코드의 가독성을 높혀주는 군요..
정리 감사합니다!

2023-01-05 17:54 UTC, kanghyun98 approved these changes

2023-01-05 18:03 UTC, yoo-jimin127 commented on 01. 프레임워크에 대한 이야기/README.md
> +    - [양방향 바인딩 VS 단방향 바인딩 - 장단점](https://velog.io/@sunaaank/data-binding)
맞아요! 
저도 자료 추천헤주셔서 읽어보니 양방향 데이터 바인딩이 AngularJS가 후퇴하게 된 이유 중 하나라고 생각했는데,
코드량을 비롯한 가독성 측면에서는 이점이 있었다는 사실을 알게 된 것 같아요!! 재밌네요...ㅋㅋㅋㅋㅋㅋ 리뷰 감사합니다!!~☺️

2023-01-09 08:04 UTC, merged